services:
  db:
    image: postgres:15
    container_name: cctv_db
    volumes:
      - postgresdata:/var/lib/postgresql/data
    env_file:
      - .env
    # ports:
    #   - 5432:5432

  # redis:
  #   image: redis:7
  #   container_name: redis

  backend:
    image: cctv_backend
    build:
      context: .
    container_name: cctv_backend
    env_file:
      - .env
    depends_on:
      - db
      # - redis
    command: ["/app/docker/entry_point.sh"]
    ports:
      - 80:8000
       
volumes:
  postgresdata:
