services:
  nginx:
    image:
      nginx:1.21-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./cctv.itmoscow.crt:/etc/nginx/ssl/cctv.itmoscow.crt
      - ./cctv.itmoscow.key:/etc/nginx/ssl/cctv.itmoscow.key
    restart: on-failure

  db:
    image: postgres:15
    container_name: cctv_db
    volumes:
      - postgresdata:/var/lib/postgresql/data
    env_file:
      - .env
    # ports:
    #   - 5432:5432

  # redis:
  #   image: redis:7
  #   container_name: redis

  backend:
    image: cctv_backend
    build:
      context: .
    container_name: cctv_backend
    env_file:
      - .env
    depends_on:
      - db
      # - redis
    command: ["/src/docker/entry_point.sh"]
    ports:
      - 8000:8000
       
volumes:
  postgresdata:
