services:
  nginx:
    image:
      nginx:1.21-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./cctv.itmoscow.key.pem:/etc/nginx/ssl/cctv.itmoscow.key.pem
      - ./cctv.itmoscow.pem:/etc/nginx/ssl/cctv.itmoscow.pem
    restart: on-failure
    depends_on:
      - cctv_backend
    networks:
      - default

  db:
    image: postgres:15
    container_name: cctv_db
    volumes:
      - postgresdata:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - default
    # ports:
    #   - 5432:5432

  rabbitmq:
    # image: rabbitmq:4-management-alpine
    image: rabbitmq:4-alpine
    container_name: 'rabbitmq'
    hostname: 'rabbitmq'
    # ports:
        # - 5672:5672
        # - 15672:15672
    volumes:
        - rabbitmq_data:/var/lib/rabbitmq/
        - rabbitmq_log:/var/log/rabbitmq

  # redis:
  #   image: redis:7
  #   container_name: redis

  backend:
    image: cctv_backend
    build:
      context: .
    volumes:
      - /home/user/screenshots:/src/app/static/screenshots
    container_name: cctv_backend
    env_file:
      - .env
    depends_on:
      - db
      - rabbitmq
      # - redis
    command: ["/src/docker/entry_point.sh"]
    ports:
      - 8000:8000
    networks:
      - default

  cctv_tg_worker:
    image: cctv_tg_worker
    # build:
    #   context: .
    volumes:
      - /home/user/screenshots:/screenshots
    container_name: cctv_tg_worker
    env_file:
      - .env
    # depends_on:
    #   - db
    #   - rabbitmq
      # - redis
    command: ["python", "main.py"]
    # ports:
    #   - 8000:8000
    networks:
       - default

       
volumes:
  postgresdata:
  rabbitmq_data:
  rabbitmq_log:

networks:
  default:
    name: cctv_network
    driver: bridge